### ISSUE TITLE
Duration in markdown appears to be mm:ss instead of hh:mm

### ISSUE THREAD

**Issue by Amy-Lynn** [googlecodelabs/tools#246] opened 2019-05-15 18:00 UTC
https://github.com/googlecodelabs/tools/blob/master/claat/parser/md/README.md and https://medium.com/@mariopce/tutorial-how-to-make-tutorials-using-google-code-labs-gangdam-style-d62b35476816 indicate duration should be `hh:mm` but when using this locally, appears to be `mm:ss`

Markdown:
![image](https://user-images.githubusercontent.com/10166933/57797956-989fad80-7719-11e9-9ee1-9ca78444a1e6.png)

Generated page:
![image](https://user-images.githubusercontent.com/10166933/57798007-b2d98b80-7719-11e9-88bb-f4419872c959.png)

Happy to submit a PR to update the docs if this is expected behavior, but wasn't sure if the docs were wrong or if the code was wrong.

**Comment by Marcial1234** [comment] 2019-05-20 19:15
I believe this is working as intended. We changed the default duration to `hh:mm:ss` a while ago (no `:` will be interpreted as `ss`, and only single colon `4:40` duration will be interpreted as `mm:ss`). We haven't updated the documentation, as we're currently in track for a major refactoring of this repo/tool, but this should still stand after that.

**Comment by cassierecher** [comment] 2019-05-20 19:44
I'm not sure expressing times down to the second is all that useful. We should reconsider this once we have time.

**Closed** 2019-05-20 22:31 UTC

**Comment by cassierecher** [comment] 2019-05-21 14:59
Thanks for the contribution!
