### ISSUE TITLE
I was asked to authorize after running "claat export"

### ISSUE THREAD

**Issue by Enjolras67** [googlecodelabs/tools#351] opened 2019-09-23 18:32 UTC
I was running "claat export example.md" to transform the doc contents. But I got 
Authorize me at following URL, please:

https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=183908478743-e8rth9fbo7juk9eeivgp23asnt791g63.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.readonly&state=unused

Code:

claat version: 1.0.4-2019-06-28T21:14:15Z-9ad41c6(downloaded as binary from the 2.2.0 github release artifacts)

**Comment by nicolasgarnier** [comment] 2019-10-01 07:43
Closing because this is a dupe of #337

**Closed by nicolasgarnier** 2019-10-01 07:43 UTC
